print("Nama panjang = Jehanifa Taufiq Alea")
print("NIM = I0322057")
print("Alamat = Penaruban, Purbalingga")
print("=========================")
print("Saya berasal dari Kabupaten Purbalingga, yang dikenal sebagai Kota Perwira")
print("Disebut Kota Perwira karena Purbalingga merupakan kota kelahiran salah satu pahlawan kemerdekaan yakni Jenderal Soedirman")
print("=========================")
print("Harapan saya setelah lulus dari teknik industri ialah semoga saya mendapatkan pekerjaan yang sesuai dengan minat dan bakat saya serta dapat memanfaatkan ilmu yang saya dapat selama kuliah untuk dapat membatu orang lain khususnya pada bidang industri")
